# -*- coding: utf-8 -*-
"""Copy of svm(2-class)_scikit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16-gpGm4n1ElbUpzi04SrP2LZiIMAX1iY
"""

from google.colab import drive

drive.mount('/content/gdrive')

import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
import random
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

path1 = '/content/gdrive/MyDrive/raw-img'
categories = ["cat","dog"]
data = []

for category in categories:
    path2 = category
    label = categories.index(category)
    path = os.path.join(path1,path2)
    for img in os.listdir(path)[1:5]:
        img_path = os.path.join(path,img)
        pet_img = cv2.imread(img_path)
        pet_img = cv2.resize(pet_img,(120,120))
        image = np.array(pet_img).flatten()
        data.append([image,label])

print(np.shape(image))
print(np.shape(data))
print(data)

features = []
labels = []

for feature, label in data:
    features.append(feature)
    labels.append(label)

print(len(features), len(labels))

import pickle

x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size = 0.25)

model = SVC(C=5, kernel = 'rbf', gamma='auto') #poly, linear
model.fit(x_train, y_train)
pick = open('model_rbf.sav' ,'wb')
pickle.dump(model,pick)
pick.close()

print(np.shape(x_test))
print(x_test)

import pickle
from sklearn.metrics import accuracy_score
pick = open('model_rbf.sav','rb')
model = pickle.load(pick)
pick.close()

prediction = model.predict(x_test)
accuracy = accuracy_score(y_test,prediction)
print(accuracy)

for i in range(10):
  pet = x_test[i]
  pet = x_test[i].reshape((120,120,3))
  plt.figure()
  plt.imshow(pet)
  print("Prediction is: ", categories[prediction[i]])

def predict_image(img):
  image = cv2.resize(pet_img,(120,120))
  img_4d = np.array(image).flatten()
  img_4d = img_4d.reshape(1,-1)
  prediction=model.predict(img_4d)
  return categories[prediction[0]]
